<?php

namespace Tests\Feature;

use App\Models\Serie;
use App\Models\User;
use App\Services\createSerie;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Illuminate\Support\Facades\Hash;
use Tests\TestCase;

class CreateSerieTest extends TestCase
{
    /**
     * A basic feature test example.
     *
     * @return void
     */

    use RefreshDatabase;

    private $user;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $userCreate = User::create([
            'name' => 'User Teste',
            'email' => 'teste@teste.com',
            'password' => Hash::make('12345'),
        ]);

        $this->user = $userCreate;
    }

    public function testCreateSerie()
    {
        $createSerie = new CreateSerie();
        $serie = $createSerie->CriarSerie(
            'Serie Teste',
            1,
            1,
            1);

        $this->assertInstanceOf(Serie::class, $serie);
        $this->assertDatabaseHas('series', ['nome' => 'Serie Teste', 'user_id' => 1]);
        $this->assertDatabaseHas('temporadas', ['serie_id' => $serie->id, 'numero' => 1]);
        $this->assertDatabaseHas('episodios', ['numero' => 1]);

    }
}
