<?php

namespace Tests\Feature;

use App\Models\User;
use App\Services\createSerie;
use App\Services\deleteSerie;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Illuminate\Support\Facades\Hash;
use Tests\TestCase;

class DeleteSerieTest extends TestCase
{
    /**
     * A basic feature test example.
     *
     * @return void
     */
    use RefreshDatabase;

    private $user;
    private $serie;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $userCreate = User::create([
            'name' => 'User Teste',
            'email' => 'teste@teste.com',
            'password' => Hash::make('12345'),
        ]);

        $this->user = $userCreate;

        $createSerie = new CreateSerie();
        $this->serie = $createSerie->CriarSerie(
            'Serie Teste',
            1,
            1,
            1);
    }

    public function testDeleteSerie()
    {
        $this->assertDatabaseHas('series',['id'=>$this->serie->id]);

        $deleteSerie = new deleteSerie();
        $serieName = $deleteSerie->DeletarSerie($this->serie->id);

        $this->assertIsString($serieName);
        $this->assertEquals('Serie Teste', $this->serie->nome);
        $this->assertDatabaseMissing('series',['id'=>$this->serie->id]);
    }
}
